/**
 * The single read path for the whole app.
 *
 * Firestore is the source of truth. The 698-document collection is fetched
 * ONCE, normalised, and held in a context; every view — map, tables, charts,
 * drawer — derives from that one array. Nothing in the app issues a query per
 * district, because at 698 documents the whole collection is cheaper than the
 * round trips would be, and hovering a map must never touch the network.
 *
 * If Firestore is not configured or the read fails, the bundled snapshot in
 * `/data/districts.json` is used and the UI says so in the status bar. The
 * fallback is generated by `scripts/build_fallback.py` from the same artefacts
 * the publisher writes, so both paths carry the same shape.
 */
import { collection, getDocs } from 'firebase/firestore';
import { firestore, isConfigured } from './firebase';
import { normaliseCode } from './names';
import type {
  DataSource, DistrictDoc, RunDoc, ValidationRow, BenchmarkRow,
  MlValidation, DataQuality, GenAiBundle, Methodology, GeoNameMap,
} from './types';

export interface Bundle {
  districts: DistrictDoc[];
  byCode: Map<string, DistrictDoc>;
  run: RunDoc | null;
  source: DataSource;
  /** why the fallback was used, when it was */
  sourceNote: string;
  fetchedAt: string;
  /** true when the documents carry the v2 fields (pillar detail, narrative) */
  isV2: boolean;
}

function asNumber(v: unknown): number {
  const n = typeof v === 'number' ? v : Number(v);
  return Number.isFinite(n) ? n : 0;
}

/** Accepts a v1 or v2 document and always returns the v2-shaped record. */
export function normaliseDoc(id: string, raw: Record<string, unknown>): DistrictDoc {
  const cvf = raw.current_vs_future as DistrictDoc['current_vs_future'];
  const interval = raw.rank_interval_p5_p95 as number[] | undefined;
  return {
    code: normaliseCode(id),
    district_name: String(raw.district_name ?? 'Unknown'),
    state_name: String(raw.state_name ?? 'Unknown'),
    population_2011:
      raw.population_2011 === null || raw.population_2011 === undefined
        ? null
        : asNumber(raw.population_2011),
    overall_score: asNumber(raw.overall_score),
    overall_rank: asNumber(raw.overall_rank),
    chronic_score: asNumber(raw.chronic_score),
    chronic_rank: asNumber(raw.chronic_rank),
    acute_score: asNumber(raw.acute_score),
    acute_rank: asNumber(raw.acute_rank),
    tier: String(raw.tier ?? '—'),
    current_vs_future: cvf,
    rank_interval_p5_p95:
      interval && interval.length === 2 ? [interval[0], interval[1]] : undefined,
    pillar_scores: raw.pillar_scores as DistrictDoc['pillar_scores'],
    size_score: raw.size_score === undefined ? undefined : asNumber(raw.size_score),
    quality_score: raw.quality_score === undefined ? undefined : asNumber(raw.quality_score),
    narrative: raw.narrative as string | undefined,
    narrative_source: raw.narrative_source as string | undefined,
    narrative_numeric_check: raw.narrative_numeric_check as string | undefined,
    run_id: raw.run_id as string | undefined,
    updated_at: raw.updated_at as string | undefined,
    is_imputed: raw.is_imputed as Record<string, number> | undefined,
    imputation_method: raw.imputation_method as string | undefined,
    data_vintage: raw.data_vintage as Record<string, string> | undefined,
    data_snapshot_id: raw.data_snapshot_id as string | undefined,
    cluster: raw.cluster as number | string | undefined,
    model_version: raw.model_version as string | undefined,
  };
}

function index(docs: DistrictDoc[]): Map<string, DistrictDoc> {
  const m = new Map<string, DistrictDoc>();
  // Both key forms are registered so a caller holding an unpadded code from a
  // CSV or a URL cannot miss. The stored `code` is always the padded form.
  for (const d of docs) {
    m.set(d.code, d);
    m.set(String(Number(d.code)), d);
  }
  return m;
}

async function fromLocal(note: string, forced: boolean): Promise<Bundle> {
  const [dRes, rRes] = await Promise.all([
    fetch('/data/districts.json'),
    fetch('/data/run.json'),
  ]);
  // A missing snapshot must say so. Without this check the 404 page's HTML is
  // handed to JSON.parse and the app dies with an unrelated syntax error —
  // which is exactly how a deploy that shipped without web/public/data/ looked.
  if (!dRes.ok || !rRes.ok) {
    throw new Error(
      `bundled snapshot missing (/data/districts.json -> ${dRes.status}, ` +
        `/data/run.json -> ${rRes.status}). It is generated by ` +
        `scripts/build_fallback.py and must be committed for the deployed ` +
        `site to have a fallback.`,
    );
  }
  const dJson = (await dRes.json()) as {
    docs: Record<string, Record<string, unknown>>;
  };
  const run = (await rRes.json()) as RunDoc;
  const districts = Object.entries(dJson.docs).map(([id, raw]) =>
    normaliseDoc(id, raw),
  );
  districts.sort((a, b) => a.overall_rank - b.overall_rank);
  return {
    districts,
    byCode: index(districts),
    run,
    source: forced ? 'local-forced' : 'local-fallback',
    sourceNote: note,
    fetchedAt: new Date().toISOString(),
    isV2: districts.some((d) => d.pillar_scores !== undefined),
  };
}

export async function loadBundle(): Promise<Bundle> {
  if (!isConfigured()) {
    return fromLocal(
      process.env.NEXT_PUBLIC_FORCE_LOCAL_DATA === 'true'
        ? 'NEXT_PUBLIC_FORCE_LOCAL_DATA=true — the bundled snapshot was requested explicitly.'
        : 'No NEXT_PUBLIC_FIREBASE_* config found, so the bundled snapshot of the same artefacts is being read instead.',
      process.env.NEXT_PUBLIC_FORCE_LOCAL_DATA === 'true',
    );
  }
  try {
    const db = firestore();
    if (!db) throw new Error('Firestore unavailable');
    const [scoresSnap, runsSnap] = await Promise.all([
      getDocs(collection(db, 'mai_scores')),
      getDocs(collection(db, 'mai_runs')),
    ]);
    if (scoresSnap.empty) throw new Error('mai_scores is empty');

    const districts = scoresSnap.docs.map((d) =>
      normaliseDoc(d.id, d.data() as Record<string, unknown>),
    );
    districts.sort((a, b) => a.overall_rank - b.overall_rank);

    // Newest run wins when several are present.
    const runs = runsSnap.docs.map((d) => ({
      model_version: d.id,
      ...(d.data() as Record<string, unknown>),
    })) as RunDoc[];
    runs.sort((a, b) =>
      String(b.created_at ?? b.model_version).localeCompare(
        String(a.created_at ?? a.model_version),
      ),
    );

    return {
      districts,
      byCode: index(districts),
      run: runs[0] ?? null,
      source: 'firestore',
      sourceNote: `Live read of mai_scores (${districts.length} documents).`,
      fetchedAt: new Date().toISOString(),
      isV2: districts.some((d) => d.pillar_scores !== undefined),
    };
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err);
    // eslint-disable-next-line no-console
    console.warn('[mai] Firestore read failed, using bundled snapshot:', msg);
    return fromLocal(`Firestore read failed (${msg}).`, false);
  }
}

/* ---------------------------------------------------------------- artefacts
 * The validation table, benchmark pack, ML falsification, coverage, crosswalk
 * review and GenAI evaluations are NOT in Firestore — they are analysis
 * artefacts, not published documents. They are always read from /data.
 */
const cache = new Map<string, unknown>();

async function json<T>(path: string): Promise<T> {
  if (cache.has(path)) return cache.get(path) as T;
  const res = await fetch(path);
  if (!res.ok) throw new Error(`${path}: ${res.status}`);
  const data = (await res.json()) as T;
  cache.set(path, data);
  return data;
}

export const loadValidation = () =>
  json<{ rows: ValidationRow[]; pass: number; fail: number }>('/data/validation.json');
export const loadBenchmarks = () =>
  json<{ rows: BenchmarkRow[]; niti_round?: string; niti_states_used?: string[] }>(
    '/data/benchmarks.json',
  );
export const loadMl = () => json<MlValidation>('/data/ml.json');
export const loadDataQuality = () => json<DataQuality>('/data/data_quality.json');
export const loadGenAi = () => json<GenAiBundle>('/data/genai.json');
export const loadMethodology = () => json<Methodology>('/data/methodology.json');
export const loadGeoNameMap = () => json<GeoNameMap>('/geo_name_map.json');
export const loadImputationFlags = () =>
  json<Record<string, Record<string, number>>>('/data/imputation_flags.json');
export const loadStateIndex = () =>
  json<Record<string, { state: string; file: string; districts: number }>>(
    '/districts/index.json',
  );
