'use client';
import Link from 'next/link';
import { usePathname } from 'next/navigation';
import { useData } from './DataProvider';
import { shortDate } from '@/lib/format';

const NAV = [
  { href: '/', label: 'Overview' },
  { href: '/map/', label: 'Map' },
  { href: '/districts/', label: 'Districts' },
  { href: '/states/', label: 'States' },
  { href: '/therapy/', label: 'Therapy split' },
  { href: '/growth/', label: 'Current vs future' },
  { href: '/deployment/', label: 'Deployment' },
  { href: '/methodology/', label: 'Methodology' },
  { href: '/validation/', label: 'Validation' },
  { href: '/genai/', label: 'GenAI layer' },
  { href: '/data-quality/', label: 'Data quality' },
];

function StatusBar() {
  const { bundle, loading, error } = useData();
  const live = bundle?.source === 'firestore';
  // A failed load is NOT "bundled snapshot". Reporting it as one is how a
  // deploy with no data at all still looked healthy in the status bar.
  const failed = !loading && !bundle;
  return (
    <div className="border-b border-line bg-page/80 backdrop-blur">
      <div className="mx-auto flex max-w-shell flex-wrap items-center gap-x-6 gap-y-1 px-6 py-1.5 text-[11px] text-dim">
        <span className="flex items-center gap-2">
          <span
            className="inline-block h-1.5 w-1.5 rounded-full"
            style={{
              background: loading
                ? '#8FA3B0'
                : failed
                  ? '#E5484D'
                  : live
                    ? '#3FB6A8'
                    : '#F2C14E',
            }}
          />
          {loading
            ? 'reading…'
            : failed
              ? 'no data loaded'
              : live
                ? 'live · Firestore mai_scores'
                : 'bundled snapshot'}
        </span>
        {failed && error && (
          <span className="text-[11px] text-ramp-6">{error}</span>
        )}
        {bundle && (
          <>
            <span className="tnum">{bundle.districts.length} districts</span>
            <span className="tnum">{bundle.run?.model_version ?? 'no run record'}</span>
            <span className="tnum">
              vintage {shortDate(bundle.run?.created_at)}
            </span>
            {!bundle.isV2 && (
              <span className="text-ramp-6">
                v1 documents — pillar detail and narratives arrive with{' '}
                <code>mai.publish --confirm</code>
              </span>
            )}
          </>
        )}
      </div>
    </div>
  );
}

/**
 * Shown in place of the page when NO data could be loaded at all.
 *
 * Every page guards on `loading || !stats`, so without this a failed load
 * renders the loading pulse forever — a missing file is indistinguishable from
 * a slow network, which is precisely how the first Netlify deploy presented.
 */
function DataFailure({ message }: { message: string }) {
  return (
    <div className="panel p-6">
      <div className="h-eyebrow mb-3 text-ramp-6">Data unavailable</div>
      <p className="max-w-3xl text-[14px] leading-relaxed text-bright">
        The index could not be read, so there is nothing to show. This page is
        not loading — it has finished and failed.
      </p>
      <p className="mt-4 max-w-3xl break-words font-mono text-[12px] leading-relaxed text-dim">
        {message}
      </p>
      <div className="mt-5 max-w-3xl text-[12px] leading-relaxed text-dim">
        <p className="mb-2 text-bright">Usual causes</p>
        <ul className="list-disc space-y-1 pl-5">
          <li>
            The bundled snapshot in <code>web/public/data/</code> was not
            deployed. It is generated by{' '}
            <code>npm run data</code> and must be committed.
          </li>
          <li>
            No <code>NEXT_PUBLIC_FIREBASE_*</code> variables are set on the
            host, and the fallback is missing too.
          </li>
          <li>
            Firestore rules do not permit anonymous reads of{' '}
            <code>mai_scores</code>.
          </li>
        </ul>
      </div>
    </div>
  );
}

export function Shell({ children }: { children: React.ReactNode }) {
  const path = usePathname();
  const { bundle, loading, error } = useData();
  const failed = !loading && !bundle;
  const isActive = (href: string) =>
    href === '/' ? path === '/' : path.startsWith(href.replace(/\/$/, ''));

  return (
    <div className="min-h-screen bg-page">
      <StatusBar />
      <header className="sticky top-0 z-40 border-b border-line bg-page/95 backdrop-blur">
        <div className="mx-auto flex max-w-shell items-center justify-between gap-6 px-6 py-3">
          <Link href="/" className="group flex items-baseline gap-3">
            <span className="font-display text-[15px] font-medium tracking-[0.14em] text-bright">
              MAI
            </span>
            <span className="hidden text-[11px] tracking-[0.16em] text-dim sm:block">
              DISTRICT MARKET ATTRACTIVENESS INDEX · v2
            </span>
          </Link>
          <nav className="flex flex-wrap items-center justify-end gap-x-4 gap-y-1">
            {NAV.map((n) => (
              <Link
                key={n.href}
                href={n.href}
                className={`text-[12px] tracking-wide transition-colors duration-[160ms] ease-out ${
                  isActive(n.href)
                    ? 'text-accent'
                    : 'text-dim hover:text-bright'
                }`}
              >
                {n.label}
              </Link>
            ))}
          </nav>
        </div>
      </header>
      <main className="mx-auto max-w-shell px-6 py-10">
        {failed ? (
          <DataFailure message={error ?? 'the index could not be read'} />
        ) : (
          children
        )}
      </main>
      <footer className="mt-16 border-t border-line">
        <div className="mx-auto max-w-shell px-6 py-8 text-[11px] leading-relaxed text-dim">
          <p>
            Built for the Trilytics 2026 challenge (Sun Pharma). Scores are read
            from Firestore at runtime; the analysis artefacts behind the
            validation, benchmark and GenAI pages are read from the build
            output of the Python pipeline in this repository.
          </p>
          <p className="mt-2">
            Every failing test is shown as failing. Nothing on this site is
            asserted that the pipeline did not compute.
          </p>
        </div>
      </footer>
    </div>
  );
}
